

apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3

  template:
    metadata:
      labels:
        app: node
    
    spec:
      containers:
      - name: nginx
        image: jka2023/sparta_app
        ports:
        - containerPort: 3000